(() => {
  "use strict";
  const CONFIG={checkoutUrl:"https://pay.wiapy.com/KX2LK3vXNU",brand:"Carnívora 40+",price:"R$ 29,90",offerMinutes:10,pixelId:"",utmifyScript:""};
  /* Preencha os caminhos abaixo com os arquivos autorizados enviados pelo cliente. */
  const ASSETS={
    logo:"/assets/logo-carnivora-40.webp",
    genderWoman:"/assets/options/etapa_01_genero_mulher.webp",
    genderMan:"/assets/options/etapa_01_genero_homem.webp",
    age18:{Mulher:"/assets/options/etapa_02_idade_mulher_18_a_26_anos.webp",Homem:"/assets/options/etapa_02_idade_homem_18_a_26_anos.webp"},
    age27:{Mulher:"/assets/options/etapa_02_idade_mulher_27_a_38_anos.webp",Homem:"/assets/options/etapa_02_idade_homem_27_a_38_anos.webp"},
    age39:{Mulher:"/assets/options/etapa_02_idade_mulher_39_a_50_anos.webp",Homem:"/assets/options/etapa_02_idade_homem_39_a_50_anos.webp"},
    age50:{Mulher:"/assets/options/etapa_02_idade_mulher_50_mais.webp",Homem:"/assets/options/etapa_02_idade_homem_50_mais.webp"},
    goalAppearance:{Mulher:"/assets/options/etapa_03_objetivo_mulher_ficar_mais_bonita_e_me_sentir_bem.webp",Homem:"/assets/options/etapa_03_objetivo_homem_ficar_mais_bonito_e_me_sentir_bem.webp"},
    goalHealth:{Mulher:"/assets/options/etapa_03_objetivo_mulher_melhorar_minha_saude.webp",Homem:"/assets/options/etapa_03_objetivo_homem_melhorar_minha_saude.webp"},
    goalBoth:{Mulher:"/assets/options/etapa_03_objetivo_mulher_ambos.webp",Homem:"/assets/options/etapa_03_objetivo_homem_ambos.webp"},
    comments:Array.from({length:12},(_,i)=>`/assets/comments/comentario_${i+1}.webp`),
    macroInfo:"assets/dieta-carnivora-80-20.jpeg",difference:"assets/dieta-carnivora-diferente.jpeg",goal:"",foodInfo:"/assets/mais-de-100-receitas.jpeg",mealPlan:"",faceChange:{Mulher:"/assets/inchaco-rosto-mulher.webp",Homem:"/assets/inchaco-rosto-homem.webp"},offerEvolution:{Mulher:"/assets/resultado-agora-meta-mulher.webp",Homem:"/assets/resultado-agora-meta-homem.webp"},visibleChange:{Mulher:"/assets/antes-depois-mulher.webp",Homem:"/assets/antes-depois-homem.webp"},guarantee:"/assets/garantia-30-dias.webp"
  };
  const KEYS=["utm_source","utm_medium","utm_campaign","utm_content","utm_term","fbclid","src"],params=new URLSearchParams(location.search),tracking=JSON.parse(sessionStorage.getItem("carnifit_tracking")||"{}");
  KEYS.forEach(k=>{if(params.get(k))tracking[k]=params.get(k)});sessionStorage.setItem("carnifit_tracking",JSON.stringify(tracking));
  const c=(label,image="")=>({label,image});
  const steps=[
    {id:"gender",type:"imageGrid",title:"Responda para receber seu plano alimentar personalizado",subtitle:"Selecione seu gênero:",options:[c("Mulher","genderWoman"),c("Homem","genderMan")]},
    {id:"age",type:"imageGrid",title:"Qual é a sua faixa etária?",options:[c("18 a 26 anos","age18"),c("27 a 38 anos","age27"),c("39 a 50 anos","age39"),c("Mais de 50 anos","age50")]},
    {id:"primaryGoal",type:"choice",iconOptions:true,title:"Qual é o seu principal objetivo com essa alimentação?",options:[c("Melhorar minha aparência","goalAppearance"),c("Cuidar melhor da saúde","goalHealth"),c("Os dois objetivos","goalBoth"),c("Outro objetivo")]},
    {id:"previousExperience",type:"choice",title:"Você já experimentou uma alimentação carnívora?",options:[c("Sim, já experimentei"),c("Já ouvi falar"),c("Ainda não experimentei"),c("Tentei, mas não consegui manter")]},
    {id:"macroInfo",type:"info",image:"macroInfo",imageOnly:true,title:"A dieta carnívora é composta por 80% gordura, 20% proteína e baixo teor de carboidratos",body:""},
    {id:"hungerTime",type:"choice",title:"Em qual período você costuma sentir mais fome?",options:[c("Manhã"),c("Tarde"),c("Noite"),c("Não existe um horário certo")]},
    {id:"favoriteMeal",type:"choice",title:"Qual refeição do dia você mais gosta?",options:[c("Café da manhã"),c("Almoço"),c("Jantar"),c("Lanches"),c("Não tenho uma refeição favorita")]},
    {id:"weightHistory",type:"choice",title:"Você já perdeu peso e depois teve dificuldade para manter?",options:[c("Sim"),c("Isso acontece com frequência"),c("Já passei pelo efeito sanfona"),c("Manter o peso é mais difícil do que emagrecer")]},
    {id:"difference",type:"info",image:"difference",imageOnly:true,title:"A dieta carnívora é diferente",body:""},
    {id:"height",type:"range",title:"Qual é a sua altura?",min:140,max:220,value:180,unit:"cm",altUnit:"pol"},
    {id:"weight",type:"range",title:"Qual é o seu peso atual?",min:40,max:250,value:70,unit:"kg",altUnit:"lb"},
    {id:"goalWeight",type:"range",title:"Qual peso você deseja alcançar?",min:40,max:250,value:65,unit:"kg",altUnit:"lb"},
    {id:"goalRegistered",type:"info",image:"goal",title:"Você definiu uma meta clara e possível de acompanhar",body:"Agora vamos considerar sua rotina e suas preferências."},
    {id:"name",type:"input",title:"Sua jornada está prestes a começar",secondaryTitle:"Como podemos chamar você?",label:"Nome",placeholder:"Digite seu nome...",inputType:"text"},
    {id:"preview",type:"result",title:"Com base em suas respostas:",body:"Você chegará ao seu objetivo em 4 semanas.",testimonials:true,testimonialStart:1},
    {id:"weeklyActivity",type:"choice",title:"Como você descreve sua atividade física semanal?",options:[c("Pouco ou nenhum exercício"),c("Levemente ativo: 1 a 2 treinos"),c("Moderadamente ativo: 3 a 5 treinos"),c("Muito ativo: 6 a 7 dias"),c("Extremamente ativo ou trabalho físico pesado")]},
    {id:"timeAway",type:"choice",title:"Há quanto tempo você está distante do peso desejado?",options:[c("Menos de 1 ano"),c("De 1 a 3 anos"),c("Mais de 3 anos"),c("Nunca estive no peso que desejo")]},
    {id:"currentSize",type:"choice",title:"Qual tamanho de roupa você costuma usar?",options:[c("XXXL+"),c("XXXL"),c("XXG"),c("GG"),c("G"),c("M"),c("P ou menor")]},
    {id:"desiredSize",type:"choice",title:"Qual tamanho de roupa você gostaria de usar?",options:[c("XXXL+"),c("XXXL"),c("XXG"),c("GG"),c("G"),c("M"),c("P ou menor")]},
    {id:"partialCalculation",type:"loading",title:"Calculando seu plano alimentar",body:"Organizando suas respostas...",testimonials:true,testimonialStart:3},
    {id:"eatingHabits",type:"choice",title:"Como você descreve seus hábitos alimentares?",options:[c("Como quase sempre as mesmas coisas"),c("Faço variações usando os mesmos alimentos"),c("Revezo alguns pratos favoritos"),c("Como de tudo um pouco"),c("Não tenho certeza")]},
    {id:"foodInfo",type:"info",image:"foodInfo",title:"Mais de 100 receitas deliciosas",body:"As sugestões serão organizadas conforme suas preferências e experiência na cozinha."},
    {id:"ingredients",type:"multi",max:5,title:"Escolha até cinco ingredientes favoritos",options:[c("Carne bovina"),c("Carne suína"),c("Frango"),c("Peixe"),c("Ovos"),c("Manteiga"),c("Sal"),c("Queijos curados"),c("Vísceras"),c("Nenhuma das opções")]},
    {id:"protein",type:"multi",max:3,title:"Quais proteínas você prefere?",options:[c("Ovos"),c("Laticínios"),c("Frango"),c("Carne bovina"),c("Carne suína"),c("Peru"),c("Peixe"),c("Cordeiro"),c("Proteína vegetal"),c("Nenhuma das alternativas")]},
    {id:"allergies",type:"multi",title:"Você possui alguma alergia ou intolerância alimentar?",options:[c("Nenhuma"),c("Lactose"),c("Oleaginosas"),c("Frutos do mar"),c("Proteína do leite"),c("Proteína do ovo"),c("Mel"),c("Cítricos"),c("Outra")]},
    {id:"mealPlan",type:"info",image:"mealPlan",title:"Seu plano de refeições está sendo organizado",body:"As receitas serão combinadas com os alimentos e preferências selecionados."},
    {id:"sleep",type:"choice",title:"Quantas horas você costuma dormir por noite?",options:[c("Mais de 8 horas"),c("7 a 8 horas"),c("5 a 6 horas"),c("Menos de 5 horas ou sono irregular")]},
    {id:"water",type:"choice",title:"Quantos copos de água você costuma beber por dia?",options:[c("1 copo ou menos"),c("2 a 3 copos"),c("4 a 5 copos"),c("6 a 7 copos"),c("8 copos ou mais")]},
    {id:"dailyActivity",type:"choice",title:"Como é o seu cotidiano?",options:[c("Bem parado, quase não caminho"),c("Equilibrado, com alguma caminhada"),c("Bem ativo, com esforço físico frequente"),c("Varia entre dias parados e ativos")]},
    {id:"medications",type:"multi",title:"Você utiliza algum destes medicamentos ou suplementos?",options:[c("Antibióticos"),c("Medicamentos para ansiedade"),c("Hormônios"),c("Vitaminas"),c("Outro"),c("Não utilizo")]},
    {id:"conditions",type:"multi",title:"Você possui alguma destas condições de saúde?",options:[c("Diabetes"),c("Refluxo"),c("Apneia do sono"),c("Pressão alta"),c("Colesterol alto"),c("Problemas renais"),c("Em recuperação de cirurgia"),c("Nenhuma das alternativas")]},
    {id:"secondaryGoal",type:"multi",title:"Além do peso, o que mais você deseja melhorar?",options:[c("Conseguir correr 5 km"),c("Sentir-me melhor diante do espelho"),c("Ter mais saúde e energia"),c("Dormir melhor"),c("Preparar-me para um evento"),c("Sentir-me bem com meu corpo"),c("Ter uma vida mais ativa"),c("Ainda não pensei nisso")]},
    {id:"faceChange",type:"info",image:"faceChange",imageOnly:true,title:"O emagrecimento não fica visível só no corpo",body:""},
    {id:"motivation",type:"result",title:"Com motivação e persistência, você pode alcançar seu objetivo até mais rápido do que imagina!",body:"Você chegará ao seu objetivo em 4 semanas.",testimonials:true,testimonialStart:5},
    {id:"building",type:"loading",title:"Criando seu plano personalizado",body:"Preparando uma sequência com base nas respostas fornecidas...",testimonials:true,testimonialStart:7}
  ];
  const state={current:Math.min(Number(sessionStorage.getItem("carnifit_step")||0),steps.length-1),answers:JSON.parse(sessionStorage.getItem("carnifit_answers")||"{}")},app=document.querySelector("#app");
  const esc=(v="")=>String(v).replace(/[&<>'"]/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;",'"':"&quot;"})[x]);
  const persist=()=>{sessionStorage.setItem("carnifit_step",String(state.current));sessionStorage.setItem("carnifit_answers",JSON.stringify(state.answers))};
  function assetPath(slot){const value=ASSETS[slot];return typeof value==="string"?value:value?.[state.answers.gender]||""}
  const asset=(slot,label="Imagem")=>assetPath(slot)?`<img class="step-image" src="${esc(assetPath(slot))}" alt="${esc(label)}" decoding="async">`:`<div class="asset-slot" data-asset-slot="${esc(slot)}"><span>${esc(label)}</span></div>`;
  const logo=()=>ASSETS.logo?`<div class="brand-lockup"><img class="brand-image" src="${esc(ASSETS.logo)}" alt="${esc(CONFIG.brand)}" width="768" height="512" decoding="async"></div>`:`<div class="brand-word">${esc(CONFIG.brand)}</div>`;
  const top=()=>`<div class="top-area"><button class="back-button" id="back" aria-label="Voltar" ${state.current===0?"hidden":""}>←</button><div class="brand-area">${logo()}</div><div class="progress-track"><span style="width:${state.current/(steps.length-1)*100}%"></span></div></div>`;
  const option=(x,i,selected,image,icon)=>`<button class="answer ${selected?"selected":""} ${image?"image-answer":""} ${icon&&x.image?"icon-answer":""}" data-option="${i}" aria-pressed="${selected}">${image?`<div class="answer-image">${asset(x.image,"")}</div>`:icon&&x.image?`<span class="mini-picture">${asset(x.image,"")}</span>`:""}<span class="answer-label">${esc(x.label)}</span><span class="answer-check">✓</span></button>`;
  const testimonials=(amount=2,start=1)=>`<section class="testimonial-area"><h2>O que as pessoas dizem:</h2><div class="testimonial-grid">${Array.from({length:amount},(_,i)=>{const number=start+i,path=ASSETS.comments[number-1];return `<article class="testimonial-slot"><img src="${esc(path)}" alt="Comentário ${number} sobre a experiência com o plano Carnívora 40+" width="720" height="480" loading="lazy" decoding="async"></article>`}).join("")}</div></section>`;
  function ruler(s,v){let ticks="";for(let n=s.min;n<=s.max;n++){const major=n%10===0,medium=!major&&n%5===0;ticks+=`<span class="ruler-tick ${major?"major":medium?"medium":"minor"}"><i></i>${major?`<b>${n}</b>`:""}</span>`}return `<div class="unit-toggle"><button class="active" type="button">${s.unit}</button><button type="button">${s.altUnit}</button></div><div class="ruler-wrap"><div class="range-bubble"><strong id="rangeValue">${v}</strong>${s.unit}</div><div class="ruler-stage"><div class="ruler-tape" id="rulerTape" style="--ruler-offset:${(v-s.min)*-15}px" aria-hidden="true">${ticks}</div><div class="ruler-marker" aria-hidden="true"><span></span></div><input id="range" type="range" min="${s.min}" max="${s.max}" step="1" value="${v}" aria-label="${esc(s.title)}"></div><div class="drag-hint" aria-hidden="true"><span class="drag-arrow drag-arrow-left">←</span><strong>Arraste para os lados</strong><span class="drag-arrow drag-arrow-right">→</span></div></div>`}
  const resultChart=()=>`<div class="result-promise"><span>Você chegará ao seu objetivo em</span><strong>4 semanas</strong></div><div class="result-chart"><svg viewBox="0 0 640 360" role="img" aria-label="Gráfico animado mostrando a evolução estimada até quatro semanas"><defs><linearGradient id="chartGradient" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#d63a31"/><stop offset=".52" stop-color="#f1b83d"/><stop offset="1" stop-color="#42b96b"/></linearGradient><linearGradient id="chartFill" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#df6a62" stop-opacity=".72"/><stop offset=".52" stop-color="#f6d36e" stop-opacity=".68"/><stop offset="1" stop-color="#83d892" stop-opacity=".68"/></linearGradient></defs><g class="chart-grid"><line x1="70" y1="55" x2="570" y2="55"/><line x1="70" y1="116" x2="570" y2="116"/><line x1="70" y1="177" x2="570" y2="177"/><line x1="70" y1="238" x2="570" y2="238"/><line x1="70" y1="300" x2="570" y2="300"/><line x1="70" y1="55" x2="70" y2="300"/><line x1="320" y1="55" x2="320" y2="300"/><line x1="570" y1="55" x2="570" y2="300"/></g><g class="chart-labels"><text x="58" y="61">100</text><text x="58" y="122">75</text><text x="58" y="183">50</text><text x="58" y="244">25</text><text x="58" y="306">0</text><text class="chart-x" x="70" y="338">Hoje</text><text class="chart-x" x="320" y="338">2 semanas</text><text class="chart-x" x="570" y="338">4 semanas</text></g><path class="chart-area" d="M70 55 C180 88 245 133 320 177 C410 235 475 281 570 300 L570 300 L70 300 Z"/><path class="chart-line" d="M70 55 C180 88 245 133 320 177 C410 235 475 281 570 300"/><g class="chart-points"><circle class="chart-halo point-one" cx="70" cy="55" r="22"/><circle class="chart-dot point-one" cx="70" cy="55" r="10"/><circle class="chart-halo point-two" cx="320" cy="177" r="22"/><circle class="chart-dot point-two" cx="320" cy="177" r="11"/><circle class="chart-halo point-three" cx="570" cy="300" r="22"/><circle class="chart-dot point-three" cx="570" cy="300" r="10"/></g><g class="chart-you"><rect x="277" y="122" width="86" height="40" rx="10"/><text x="320" y="149">Você</text></g></svg></div>`;
  let stepLoadingId;
  function startStepLoading(){const ring=document.querySelector("#loadingRing"),ringValue=document.querySelector("#loadingRingValue"),bar=document.querySelector("#loadingBar"),percent=document.querySelector("#loadingPercent"),status=document.querySelector("#loadingStatus"),button=document.querySelector("#continue");if(!ring||!ringValue||!bar||!percent||!status||!button)return;const phases=["Analisando suas respostas...","Combinando suas preferências...","Montando seu plano personalizado...","Finalizando os últimos detalhes..."];const started=Date.now(),duration=3200;button.disabled=true;clearInterval(stepLoadingId);const update=()=>{const progress=Math.min(100,Math.round((Date.now()-started)/duration*100));ring.style.setProperty("--progress",progress);bar.style.width=`${progress}%`;percent.textContent=`${progress}%`;status.textContent=phases[Math.min(phases.length-1,Math.floor(progress/26))];if(progress>=100){clearInterval(stepLoadingId);ring.classList.add("done");ringValue.textContent="✓";status.textContent="Plano personalizado concluído!";button.disabled=false}};update();stepLoadingId=setInterval(update,40)}
  function renderStep(){clearInterval(stepLoadingId);const s=steps[state.current];let h=`<h1>${esc(s.title)}</h1>${s.secondaryTitle?`<h2 class="secondary-title">${esc(s.secondaryTitle)}</h2>`:""}${s.subtitle?`<p class="lead">${esc(s.subtitle)}</p>`:""}`;
    if(["choice","multi","imageGrid"].includes(s.type)){const saved=new Set(Array.isArray(state.answers[s.id])?state.answers[s.id]:state.answers[s.id]?[state.answers[s.id]]:[]),image=s.type==="imageGrid";h+=`<div class="answers ${image?"image-grid":""}">${s.options.map((x,i)=>option(x,i,saved.has(x.label),image,s.iconOptions)).join("")}</div>${s.type==="multi"?`<button class="continue-button" id="continue" ${saved.size?"":"disabled"}>Continuar</button>`:""}`}
    else if(s.type==="range")h+=ruler(s,state.answers[s.id]??s.value)+`<button class="continue-button" id="continue">Continuar</button>`;
    else if(s.type==="input")h+=`<label class="field-label" for="field">${esc(s.label)}</label><input class="field" id="field" type="${s.inputType}" value="${esc(state.answers[s.id]||"")}" placeholder="${esc(s.placeholder)}">${s.privacy?`<p class="privacy"><strong>Seus dados são protegidos.</strong><br>O e-mail será usado somente para informações relacionadas ao acesso.</p>`:""}<button class="continue-button" id="continue" disabled>Continuar</button>`;
    else if(s.type==="info")h=s.imageOnly?`<div class="info-image info-image-only">${asset(s.image,s.title)}</div><button class="continue-button" id="continue">Continuar</button>`:`${assetPath(s.image)?`<div class="info-image">${asset(s.image,s.title)}</div>`:""}<h1>${esc(s.title)}</h1><p class="info-copy">${esc(s.body)}</p><button class="continue-button" id="continue">Continuar</button>`;
    else if(s.type==="result")h+=`${resultChart()}${testimonials(2,s.testimonialStart)}<button class="continue-button" id="continue">Continuar</button>`;
    else if(s.type==="loading")h=`<div class="loading-ring" id="loadingRing" style="--progress:0"><span id="loadingRingValue">0%</span></div><h1>${esc(s.title)}</h1><div class="calculation"><div><span id="loadingBar" style="width:0%"></span></div><strong id="loadingPercent">0%</strong><p id="loadingStatus">${esc(s.body)}</p></div>${s.testimonials?testimonials(2,s.testimonialStart):""}<button class="continue-button" id="continue" disabled>Continuar</button>`;
    app.innerHTML=`<main class="quiz-page">${top()}<section class="question-card">${h}</section><footer>© 2026 ${esc(CONFIG.brand)}</footer></main>`;bind(s);window.scrollTo({top:0})}
  function next(){if(state.current===steps.length-1){sessionStorage.setItem("carnifit_completed","1");renderOffer();return}state.current++;persist();renderStep()}
  function bind(s){document.querySelector("#back")?.addEventListener("click",()=>{state.current=Math.max(0,state.current-1);persist();renderStep()});document.querySelectorAll("[data-option]").forEach(b=>b.addEventListener("click",()=>{const picked=s.options[Number(b.dataset.option)].label;if(s.type==="multi"){const saved=new Set(state.answers[s.id]||[]),exclusive=/nenhuma|não utilizo/i.test(picked);if(exclusive){saved.clear();saved.add(picked)}else{[...saved].filter(x=>/nenhuma|não utilizo/i.test(x)).forEach(x=>saved.delete(x));saved.has(picked)?saved.delete(picked):(!s.max||saved.size<s.max)&&saved.add(picked)}state.answers[s.id]=[...saved];persist();renderStep()}else{state.answers[s.id]=picked;persist();next()}}));const range=document.querySelector("#range");if(range){const syncRuler=()=>{document.querySelector("#rangeValue").textContent=range.value;document.querySelector("#rulerTape")?.style.setProperty("--ruler-offset",`${(Number(range.value)-s.min)*-15}px`)};range.addEventListener("input",syncRuler);document.querySelector("#continue").addEventListener("click",()=>{state.answers[s.id]=Number(range.value);persist();next()})}const field=document.querySelector("#field");if(field){const btn=document.querySelector("#continue"),valid=()=>s.inputType==="email"?/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(field.value.trim()):field.value.trim().length>=2,sync=()=>btn.disabled=!valid();field.addEventListener("input",sync);sync();btn.addEventListener("click",()=>{if(!valid())return;state.answers[s.id]=field.value.trim();persist();next()})}if(["info","result","loading","multi"].includes(s.type))document.querySelector("#continue")?.addEventListener("click",next);if(s.type==="loading")startStepLoading()}
  function checkout(){const u=new URL(CONFIG.checkoutUrl);Object.entries(tracking).forEach(([k,v])=>v&&u.searchParams.set(k,v));return u.toString()}
  function personalizedPriorities(){
    const a=state.answers,candidates=[],add=(score,pain,solution)=>candidates.push({score,pain,solution});
    const target=Number(a.goalWeight),current=Number(a.weight);
    const goal=target?{pain:`Sua meta registrada: ${target} kg`,solution:`Você respondeu que quer chegar aos ${target} kg${current?` partindo de ${current} kg`:""}. Seu plano de 4 semanas foi organizado para ajudar você a avançar nessa direção.`}:{pain:"Sua meta de peso",solution:"Seu plano de 4 semanas organiza ações práticas para ajudar você a avançar em direção ao peso desejado."};
    if(a.weightHistory)add(95,"Dificuldade para manter o peso",`Você respondeu: “${a.weightHistory}”. A solução inclui uma estratégia de continuidade para tornar a rotina mais sustentável após as primeiras semanas.`);
    if(a.timeAway)add(/Mais de 3|Nunca/.test(a.timeAway)?90:/1 a 3/.test(a.timeAway)?78:55,"Tempo distante do peso desejado",`Você está ${a.timeAway.toLowerCase()} distante da sua meta. O plano divide o processo em passos menores para facilitar a retomada da constância.`);
    if(a.hungerTime)add(72,"Fome ao longo do dia",`Você sente mais fome no período da ${a.hungerTime.toLowerCase()}. As refeições serão organizadas para dar mais estrutura justamente nesse horário.`);
    if(a.eatingHabits)add(66,"Rotina alimentar atual",`Você contou que “${a.eatingHabits.toLowerCase()}”. O plano traz opções práticas alinhadas a esse comportamento para reduzir a dificuldade de seguir a rotina.`);
    if(a.sleep&&/Menos de 5|5 a 6|irregular/.test(a.sleep))add(/Menos de 5|irregular/.test(a.sleep)?88:76,"Sono abaixo do ideal",`Você dorme ${a.sleep.toLowerCase()}. O plano inclui uma meta diária de sono para ajudar a organizar melhor sua rotina.`);
    if(a.water&&/1 copo|2 a 3|4 a 5/.test(a.water))add(/1 copo/.test(a.water)?87:/2 a 3/.test(a.water)?79:68,"Baixo consumo de água",`Você bebe ${a.water.toLowerCase()} por dia. O plano inclui uma meta progressiva de hidratação fácil de acompanhar.`);
    const activity=a.dailyActivity||a.weeklyActivity;
    if(activity&&/parado|Pouco|nenhum|Levemente/.test(activity))add(/parado|Pouco|nenhum/.test(activity)?84:70,"Pouca atividade na rotina",`Você descreveu sua rotina como “${activity.toLowerCase()}”. O plano propõe metas simples e compatíveis com o seu nível atual.`);
    const allergies=(Array.isArray(a.allergies)?a.allergies:[]).filter(x=>!/^Nenhuma$/i.test(x));
    if(allergies.length)add(92,"Restrições alimentares informadas",`Você indicou ${allergies.join(", ").toLowerCase()}. As sugestões serão filtradas para respeitar essas restrições alimentares.`);
    if(a.currentSize&&a.desiredSize&&a.currentSize!==a.desiredSize)add(62,"Meta de tamanho de roupa",`Você quer sair do tamanho ${a.currentSize} e chegar ao ${a.desiredSize}. Essa meta ficará visível para facilitar o acompanhamento da evolução.`);
    const extraGoal=Array.isArray(a.secondaryGoal)?a.secondaryGoal[0]:a.secondaryGoal;
    if(extraGoal&&extraGoal!=="Ainda não pensei nisso")add(58,"Objetivo além do peso",`Você também quer ${extraGoal.toLowerCase()}. O plano considera esse objetivo na organização das metas da sua rotina.`);
    return [goal,...candidates.sort((x,y)=>y.score-x.score).slice(0,5)];
  }
  const timer=()=>`<div class="offer-timer" role="timer" aria-label="Tempo desta sessão"><span class="timer-label">Tempo para concluir esta sessão</span><div class="timer-digits"><span><strong data-timer-minutes>${String(CONFIG.offerMinutes).padStart(2,"0")}</strong><small>min</small></span><b>:</b><span><strong data-timer-seconds>00</strong><small>seg</small></span></div></div>`;
  const buyBox=()=>`<div class="buy-box"><div class="price-kicker">ACESSO COMPLETO AO PLANO</div><div class="price-row"><div><span>Pagamento único</span><strong>${esc(CONFIG.price)}</strong><small>à vista</small></div><b>10% off</b></div><a class="buy-button" href="${esc(checkout())}">RECEBER O MEU PLANO ALIMENTAR</a><p class="secure-purchase">🔒 Compra segura e acesso após a confirmação do pagamento</p></div>`;
  let offerTimerId;
  function startOfferTimer(){
    const key="carnifit_offer_deadline";
    let deadline=Number(sessionStorage.getItem(key));
    if(!deadline||deadline<=Date.now()){deadline=Date.now()+CONFIG.offerMinutes*60*1000;sessionStorage.setItem(key,String(deadline))}
    clearInterval(offerTimerId);
    const update=()=>{const left=Math.max(0,deadline-Date.now()),minutes=Math.floor(left/60000),seconds=Math.floor(left%60000/1000);document.querySelectorAll("[data-timer-minutes]").forEach(x=>x.textContent=String(minutes).padStart(2,"0"));document.querySelectorAll("[data-timer-seconds]").forEach(x=>x.textContent=String(seconds).padStart(2,"0"));if(left===0)clearInterval(offerTimerId)};
    update();offerTimerId=setInterval(update,1000);
  }
  function renderOffer(){
    const name=esc((state.answers.name||"").split(" ")[0]);
    const priorities=personalizedPriorities();
    app.innerHTML=`<main class="offer-page">
      <section class="offer-hero"><div class="offer-container offer-narrow">${logo()}${assetPath("offerEvolution")?`<div class="offer-progress-image">${asset("offerEvolution","Comparação visual entre a condição atual e a meta")}</div>`:""}<div class="condition"><div><span>Sua condição atual</span><strong>25%</strong></div><i>→</i><div><span>Seu potencial de consistência</span><strong>90%</strong></div></div>${timer()}<h1>${name?`${name}, seu`:"Seu"} plano alimentar personalizado está pronto!</h1><p class="hero-copy">Organizamos suas respostas em uma experiência prática para acompanhar pelo celular.</p>${buyBox()}</div></section>
      <section><div class="offer-container offer-narrow"><h3 class="included-title">O seu plano foi preparado para estas prioridades:</h3><p class="personalized-intro">Selecionamos os pontos mais importantes com base nas respostas que você acabou de fornecer.</p><ul class="inclusion-list personalized-list">${priorities.map(x=>`<li><span>✓</span><div><small>DOR IDENTIFICADA</small><strong>${esc(x.pain)}</strong><p>${esc(x.solution)}</p></div></li>`).join("")}</ul>${timer()}${buyBox()}</div></section>
      <section class="visual-section"><div class="offer-container offer-narrow"><p class="eyebrow">UMA EXPERIÊNCIA VISUAL E SIMPLES</p><h2>Veja as mudanças que uma rotina consistente pode apoiar</h2><div class="wide-image">${asset("visibleChange","Imagem de antes e depois")}</div></div></section>
      <section><div class="offer-container offer-narrow"><p class="eyebrow">HISTÓRIAS REAIS</p><h2>Veja a experiência de quem já começou</h2>${testimonials(4,9)}${timer()}${buyBox()}</div></section>
      <section class="faq-section"><div class="offer-container offer-narrow"><h2>Ficou com alguma dúvida?</h2><p class="centered">Veja as perguntas mais frequentes</p><div class="faq"><details open><summary>O que encontrarei no plano?</summary><p>Refeições, receitas, organização de compras, metas e conteúdos complementares.</p></details><details><summary>Como minhas respostas são utilizadas?</summary><p>Elas ajudam a organizar a experiência conforme seu objetivo, rotina e preferências registradas.</p></details><details><summary>Quando recebo o acesso?</summary><p>O acesso é liberado conforme as informações exibidas no checkout após a confirmação do pagamento.</p></details><details><summary>Consigo acompanhar pelo celular?</summary><p>Sim. O conteúdo foi estruturado para consulta em telas de celular.</p></details><details><summary>Preciso fazer exercícios?</summary><p>A atividade física é complementar e deve respeitar seus limites e a orientação de um profissional.</p></details><details><summary>Os resultados são iguais para todo mundo?</summary><p>Não. Resultados variam conforme rotina, características individuais e constância.</p></details></div></div></section>
      <section><div class="offer-container offer-narrow guarantee"><div class="guarantee-image">${asset("guarantee","Imagem autorizada da garantia")}</div><div><p class="eyebrow">COMPRA PROTEGIDA</p><h2>Garantia de reembolso</h2><p>Consulte no checkout o prazo e todas as condições aplicáveis à garantia.</p></div></div></section>
      <section class="last-call"><div class="offer-container offer-narrow"><p class="eyebrow">SEU PLANO JÁ ESTÁ PRONTO</p><h2>Comece quando estiver preparado</h2><p class="centered">Revise os detalhes e conclua o acesso pelo ambiente seguro de pagamento.</p>${timer()}${buyBox()}</div></section>
      <footer>© 2026 ${esc(CONFIG.brand)}. Conteúdo educativo. Resultados variam.</footer>
    </main>`;
    window.scrollTo({top:0});startOfferTimer();
  }
  if(location.hash==="#oferta"||sessionStorage.getItem("carnifit_completed")==="1")renderOffer();else renderStep();
})();
