(() => {
  "use strict";
  const CONFIG={checkoutUrl:"https://pay.wiapy.com/KX2LK3vXNU",brand:"CarniFit",price:"R$ 29,90",offerMinutes:10,pixelId:"",utmifyScript:""};
  /* Preencha os caminhos abaixo com os arquivos autorizados enviados pelo cliente. */
  const ASSETS={logo:"",genderWoman:"",genderMan:"",age18:"",age27:"",age39:"",age50:"",macroInfo:"assets/dieta-carnivora-80-20.jpeg",difference:"assets/dieta-carnivora-diferente.jpeg",goal:"",foodInfo:"",mealPlan:"",faceChange:"",visibleChange:"",guarantee:""};
  const KEYS=["utm_source","utm_medium","utm_campaign","utm_content","utm_term","fbclid","src"],params=new URLSearchParams(location.search),tracking=JSON.parse(sessionStorage.getItem("carnifit_tracking")||"{}");
  KEYS.forEach(k=>{if(params.get(k))tracking[k]=params.get(k)});sessionStorage.setItem("carnifit_tracking",JSON.stringify(tracking));
  const c=(label,image="")=>({label,image});
  const steps=[
    {id:"gender",type:"imageGrid",title:"Responda para receber seu plano alimentar personalizado",subtitle:"Selecione seu gênero:",options:[c("Mulher","genderWoman"),c("Homem","genderMan")]},
    {id:"age",type:"imageGrid",title:"Qual é a sua faixa etária?",options:[c("18 a 26 anos","age18"),c("27 a 38 anos","age27"),c("39 a 50 anos","age39"),c("Mais de 50 anos","age50")]},
    {id:"primaryGoal",type:"choice",iconOptions:true,title:"Qual é o seu principal objetivo com essa alimentação?",options:[c("Melhorar minha aparência"),c("Cuidar melhor da saúde"),c("Os dois objetivos"),c("Outro objetivo")]},
    {id:"previousExperience",type:"choice",title:"Você já experimentou uma alimentação carnívora?",options:[c("Sim, já experimentei"),c("Já ouvi falar"),c("Ainda não experimentei"),c("Tentei, mas não consegui manter")]},
    {id:"macroInfo",type:"info",image:"macroInfo",imageOnly:true,title:"A dieta carnívora é composta por 80% gordura, 20% proteína e baixo teor de carboidratos",body:""},
    {id:"hungerTime",type:"choice",title:"Em qual período você costuma sentir mais fome?",options:[c("Manhã"),c("Tarde"),c("Noite"),c("Não existe um horário certo")]},
    {id:"favoriteMeal",type:"choice",title:"Qual refeição do dia você mais gosta?",options:[c("Café da manhã"),c("Almoço"),c("Jantar"),c("Lanches"),c("Não tenho uma refeição favorita")]},
    {id:"weightHistory",type:"choice",title:"Você já perdeu peso e depois teve dificuldade para manter?",options:[c("Sim"),c("Isso acontece com frequência"),c("Já passei pelo efeito sanfona"),c("Manter o peso é mais difícil do que emagrecer")]},
    {id:"difference",type:"info",image:"difference",imageOnly:true,title:"A dieta carnívora é diferente",body:""},
    {id:"height",type:"range",title:"Qual é a sua altura?",min:140,max:220,value:180,unit:"cm",altUnit:"pol"},
    {id:"weight",type:"range",title:"Qual é o seu peso atual?",min:40,max:250,value:70,unit:"kg",altUnit:"lb"},
    {id:"goalWeight",type:"range",title:"Qual peso você deseja alcançar?",min:40,max:250,value:65,unit:"kg",altUnit:"lb"},
    {id:"goalRegistered",type:"info",image:"goal",title:"Você definiu uma meta clara e possível de acompanhar",body:"Agora vamos considerar sua rotina e suas preferências."},
    {id:"name",type:"input",title:"Sua jornada está prestes a começar",secondaryTitle:"Como podemos chamar você?",label:"Nome",placeholder:"Digite seu nome...",inputType:"text"},
    {id:"preview",type:"result",title:"Com base nas respostas fornecidas",body:"Sua estimativa será ajustada ao peso, à meta e aos hábitos registrados.",testimonials:true},
    {id:"weeklyActivity",type:"choice",title:"Como você descreve sua atividade física semanal?",options:[c("Pouco ou nenhum exercício"),c("Levemente ativo: 1 a 2 treinos"),c("Moderadamente ativo: 3 a 5 treinos"),c("Muito ativo: 6 a 7 dias"),c("Extremamente ativo ou trabalho físico pesado")]},
    {id:"timeAway",type:"choice",title:"Há quanto tempo você está distante do peso desejado?",options:[c("Menos de 1 ano"),c("De 1 a 3 anos"),c("Mais de 3 anos"),c("Nunca estive no peso que desejo")]},
    {id:"currentSize",type:"choice",title:"Qual tamanho de roupa você costuma usar?",options:[c("XXXL+"),c("XXXL"),c("XXG"),c("GG"),c("G"),c("M"),c("P ou menor")]},
    {id:"desiredSize",type:"choice",title:"Qual tamanho de roupa você gostaria de usar?",options:[c("XXXL+"),c("XXXL"),c("XXG"),c("GG"),c("G"),c("M"),c("P ou menor")]},
    {id:"partialCalculation",type:"loading",title:"Calculando seu plano alimentar",body:"Organizando suas respostas...",testimonials:true},
    {id:"eatingHabits",type:"choice",title:"Como você descreve seus hábitos alimentares?",options:[c("Como quase sempre as mesmas coisas"),c("Faço variações usando os mesmos alimentos"),c("Revezo alguns pratos favoritos"),c("Como de tudo um pouco"),c("Não tenho certeza")]},
    {id:"foodInfo",type:"info",image:"foodInfo",title:"Refeições simples também podem ser saborosas",body:"As sugestões serão organizadas conforme suas preferências e experiência na cozinha."},
    {id:"ingredients",type:"multi",max:5,title:"Escolha até cinco ingredientes favoritos",options:[c("Carne bovina"),c("Carne suína"),c("Frango"),c("Peixe"),c("Ovos"),c("Manteiga"),c("Sal"),c("Queijos curados"),c("Vísceras"),c("Nenhuma das opções")]},
    {id:"protein",type:"multi",max:3,title:"Quais proteínas você prefere?",options:[c("Ovos"),c("Laticínios"),c("Frango"),c("Carne bovina"),c("Carne suína"),c("Peru"),c("Peixe"),c("Cordeiro"),c("Proteína vegetal"),c("Nenhuma das alternativas")]},
    {id:"allergies",type:"multi",title:"Você possui alguma alergia ou intolerância alimentar?",options:[c("Nenhuma"),c("Lactose"),c("Oleaginosas"),c("Frutos do mar"),c("Proteína do leite"),c("Proteína do ovo"),c("Mel"),c("Cítricos"),c("Outra")]},
    {id:"mealPlan",type:"info",image:"mealPlan",title:"Seu plano de refeições está sendo organizado",body:"As receitas serão combinadas com os alimentos e preferências selecionados."},
    {id:"sleep",type:"choice",title:"Quantas horas você costuma dormir por noite?",options:[c("Mais de 8 horas"),c("7 a 8 horas"),c("5 a 6 horas"),c("Menos de 5 horas ou sono irregular")]},
    {id:"water",type:"choice",title:"Quantos copos de água você costuma beber por dia?",options:[c("1 copo ou menos"),c("2 a 3 copos"),c("4 a 5 copos"),c("6 a 7 copos"),c("8 copos ou mais")]},
    {id:"dailyActivity",type:"choice",title:"Como é o seu cotidiano?",options:[c("Bem parado, quase não caminho"),c("Equilibrado, com alguma caminhada"),c("Bem ativo, com esforço físico frequente"),c("Varia entre dias parados e ativos")]},
    {id:"medications",type:"multi",title:"Você utiliza algum destes medicamentos ou suplementos?",options:[c("Antibióticos"),c("Medicamentos para ansiedade"),c("Hormônios"),c("Vitaminas"),c("Outro"),c("Não utilizo")]},
    {id:"conditions",type:"multi",title:"Você possui alguma destas condições de saúde?",options:[c("Diabetes"),c("Refluxo"),c("Apneia do sono"),c("Pressão alta"),c("Colesterol alto"),c("Problemas renais"),c("Em recuperação de cirurgia"),c("Nenhuma das alternativas")]},
    {id:"secondaryGoal",type:"multi",title:"Além do peso, o que mais você deseja melhorar?",options:[c("Conseguir correr 5 km"),c("Sentir-me melhor diante do espelho"),c("Ter mais saúde e energia"),c("Dormir melhor"),c("Preparar-me para um evento"),c("Sentir-me bem com meu corpo"),c("Ter uma vida mais ativa"),c("Ainda não pensei nisso")]},
    {id:"faceChange",type:"info",image:"faceChange",title:"Mudanças de rotina podem refletir além da balança",body:"Cada pessoa responde de uma forma. Sono, hidratação, alimentação e constância também influenciam a aparência."},
    {id:"motivation",type:"result",title:"Com motivação e persistência, você pode avançar mais do que imagina",body:"Sua estimativa aparecerá junto do plano final.",testimonials:true},
    {id:"building",type:"loading",title:"Criando seu plano personalizado",body:"Preparando uma sequência com base nas respostas fornecidas...",testimonials:true},
    {id:"email",type:"input",title:"Digite seu e-mail para receber o plano personalizado",label:"E-mail",placeholder:"Digite seu e-mail...",inputType:"email",privacy:true}
  ];
  const state={current:Math.min(Number(sessionStorage.getItem("carnifit_step")||0),steps.length-1),answers:JSON.parse(sessionStorage.getItem("carnifit_answers")||"{}")},app=document.querySelector("#app");
  const esc=(v="")=>String(v).replace(/[&<>'"]/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;",'"':"&quot;"})[x]);
  const persist=()=>{sessionStorage.setItem("carnifit_step",String(state.current));sessionStorage.setItem("carnifit_answers",JSON.stringify(state.answers))};
  const asset=(slot,label="Imagem")=>ASSETS[slot]?`<img class="step-image" src="${esc(ASSETS[slot])}" alt="${esc(label)}">`:`<div class="asset-slot" data-asset-slot="${esc(slot)}"><span>${esc(label)}</span></div>`;
  const logo=()=>ASSETS.logo?`<img class="brand-image" src="${esc(ASSETS.logo)}" alt="${esc(CONFIG.brand)}">`:`<div class="brand-word"><span>CARNI</span>FIT</div>`;
  const top=()=>`<div class="top-area"><button class="back-button" id="back" aria-label="Voltar" ${state.current===0?"hidden":""}>←</button><div class="brand-area">${logo()}</div><div class="progress-track"><span style="width:${state.current/(steps.length-1)*100}%"></span></div></div>`;
  const option=(x,i,selected,image,icon)=>`<button class="answer ${selected?"selected":""} ${image?"image-answer":""} ${icon?"icon-answer":""}" data-option="${i}" aria-pressed="${selected}">${image?`<div class="answer-image">${asset(x.image,x.label)}</div>`:icon?`<span class="mini-picture"></span>`:""}<span class="answer-label">${esc(x.label)}</span><span class="answer-check">✓</span></button>`;
  const testimonials=(amount=2)=>`<section class="testimonial-area"><h2>O que as pessoas dizem:</h2><div class="testimonial-grid">${Array.from({length:amount},(_,i)=>`<article class="testimonial-slot"><div class="avatar-slot"></div><div><strong>Comentário autorizado ${i+1}</strong><span>@perfil</span><p>O depoimento e a fotografia enviados por você entrarão aqui.</p></div></article>`).join("")}</div></section>`;
  function ruler(s,v){let ticks="";for(let n=s.min;n<=s.max;n+=10)ticks+=`<span>${n}</span>`;return `<div class="unit-toggle"><button class="active" type="button">${s.unit}</button><button type="button">${s.altUnit}</button></div><div class="ruler-wrap"><div class="ruler-numbers" aria-hidden="true">${ticks}</div><div class="ruler-line" aria-hidden="true"></div><input id="range" type="range" min="${s.min}" max="${s.max}" value="${v}" aria-label="${esc(s.title)}"><div class="range-bubble"><strong id="rangeValue">${v}</strong>${s.unit}</div><div class="drag-hint" aria-hidden="true"><span class="drag-arrow drag-arrow-left">←</span><strong>Arraste para os lados</strong><span class="drag-arrow drag-arrow-right">→</span></div></div>`}
  function renderStep(){const s=steps[state.current];let h=`<h1>${esc(s.title)}</h1>${s.secondaryTitle?`<h2 class="secondary-title">${esc(s.secondaryTitle)}</h2>`:""}${s.subtitle?`<p class="lead">${esc(s.subtitle)}</p>`:""}`;
    if(["choice","multi","imageGrid"].includes(s.type)){const saved=new Set(Array.isArray(state.answers[s.id])?state.answers[s.id]:state.answers[s.id]?[state.answers[s.id]]:[]),image=s.type==="imageGrid";h+=`<div class="answers ${image?"image-grid":""}">${s.options.map((x,i)=>option(x,i,saved.has(x.label),image,s.iconOptions)).join("")}</div>${s.type==="multi"?`<button class="continue-button" id="continue" ${saved.size?"":"disabled"}>Continuar</button>`:""}`}
    else if(s.type==="range")h+=ruler(s,state.answers[s.id]??s.value)+`<button class="continue-button" id="continue">Continuar</button>`;
    else if(s.type==="input")h+=`<label class="field-label" for="field">${esc(s.label)}</label><input class="field" id="field" type="${s.inputType}" value="${esc(state.answers[s.id]||"")}" placeholder="${esc(s.placeholder)}">${s.privacy?`<p class="privacy"><strong>Seus dados são protegidos.</strong><br>O e-mail será usado somente para informações relacionadas ao acesso.</p>`:""}<button class="continue-button" id="continue" disabled>Continuar</button>`;
    else if(s.type==="info")h=s.imageOnly?`<div class="info-image info-image-only">${asset(s.image,s.title)}</div><button class="continue-button" id="continue">Continuar</button>`:`<div class="info-image">${asset(s.image,s.title)}</div><h1>${esc(s.title)}</h1><p class="info-copy">${esc(s.body)}</p><button class="continue-button" id="continue">Continuar</button>`;
    else if(s.type==="result"){const weeks=Math.max(4,Math.ceil(Math.max(1,Number(state.answers.weight||70)-Number(state.answers.goalWeight||65))/2));h+=`<p class="info-copy">${esc(s.body)}</p><div class="estimate-card"><span>Estimativa inicial</span><strong>${weeks} semanas</strong></div>${testimonials()}<button class="continue-button" id="continue">Continuar</button>`}
    else if(s.type==="loading")h=`<div class="loading-ring"><span>✓</span></div><h1>${esc(s.title)}</h1><div class="calculation"><div><span></span></div><strong>100%</strong><p>${esc(s.body)}</p></div>${s.testimonials?testimonials():""}<button class="continue-button" id="continue">Continuar</button>`;
    app.innerHTML=`<main class="quiz-page">${top()}<section class="question-card">${h}</section><footer>© 2026 ${esc(CONFIG.brand)}</footer></main>`;bind(s);window.scrollTo({top:0})}
  function next(){if(state.current===steps.length-1){sessionStorage.setItem("carnifit_completed","1");renderOffer();return}state.current++;persist();renderStep()}
  function bind(s){document.querySelector("#back")?.addEventListener("click",()=>{state.current=Math.max(0,state.current-1);persist();renderStep()});document.querySelectorAll("[data-option]").forEach(b=>b.addEventListener("click",()=>{const picked=s.options[Number(b.dataset.option)].label;if(s.type==="multi"){const saved=new Set(state.answers[s.id]||[]),exclusive=/nenhuma|não utilizo/i.test(picked);if(exclusive){saved.clear();saved.add(picked)}else{[...saved].filter(x=>/nenhuma|não utilizo/i.test(x)).forEach(x=>saved.delete(x));saved.has(picked)?saved.delete(picked):(!s.max||saved.size<s.max)&&saved.add(picked)}state.answers[s.id]=[...saved];persist();renderStep()}else{state.answers[s.id]=picked;persist();next()}}));const range=document.querySelector("#range");if(range){range.addEventListener("input",()=>document.querySelector("#rangeValue").textContent=range.value);document.querySelector("#continue").addEventListener("click",()=>{state.answers[s.id]=Number(range.value);persist();next()})}const field=document.querySelector("#field");if(field){const btn=document.querySelector("#continue"),valid=()=>s.inputType==="email"?/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(field.value.trim()):field.value.trim().length>=2,sync=()=>btn.disabled=!valid();field.addEventListener("input",sync);sync();btn.addEventListener("click",()=>{if(!valid())return;state.answers[s.id]=field.value.trim();persist();next()})}if(["info","result","loading","multi"].includes(s.type))document.querySelector("#continue")?.addEventListener("click",next)}
  function checkout(){const u=new URL(CONFIG.checkoutUrl);Object.entries(tracking).forEach(([k,v])=>v&&u.searchParams.set(k,v));return u.toString()}
  const timer=()=>`<div class="offer-timer" role="timer" aria-label="Tempo desta sessão"><span class="timer-label">Tempo para concluir esta sessão</span><div class="timer-digits"><span><strong data-timer-minutes>${String(CONFIG.offerMinutes).padStart(2,"0")}</strong><small>min</small></span><b>:</b><span><strong data-timer-seconds>00</strong><small>seg</small></span></div></div>`;
  const buyBox=()=>`<div class="buy-box"><div class="price-kicker">ACESSO COMPLETO AO PLANO</div><div class="price-row"><div><span>Pagamento único</span><strong>${esc(CONFIG.price)}</strong><small>à vista</small></div><b>10% off</b></div><a class="buy-button" href="${esc(checkout())}">RECEBER O MEU PLANO ALIMENTAR</a><p class="secure-purchase">🔒 Compra segura e acesso após a confirmação do pagamento</p></div>`;
  let offerTimerId;
  function startOfferTimer(){
    const key="carnifit_offer_deadline";
    let deadline=Number(sessionStorage.getItem(key));
    if(!deadline||deadline<=Date.now()){deadline=Date.now()+CONFIG.offerMinutes*60*1000;sessionStorage.setItem(key,String(deadline))}
    clearInterval(offerTimerId);
    const update=()=>{const left=Math.max(0,deadline-Date.now()),minutes=Math.floor(left/60000),seconds=Math.floor(left%60000/1000);document.querySelectorAll("[data-timer-minutes]").forEach(x=>x.textContent=String(minutes).padStart(2,"0"));document.querySelectorAll("[data-timer-seconds]").forEach(x=>x.textContent=String(seconds).padStart(2,"0"));if(left===0)clearInterval(offerTimerId)};
    update();offerTimerId=setInterval(update,1000);
  }
  function renderOffer(){
    const name=esc((state.answers.name||"").split(" ")[0]);
    const items=["Plano de refeições organizado conforme suas preferências","Receitas práticas para consultar no celular","Lista de alimentos e orientação para compras","Sugestões para café da manhã, almoço e jantar","Estratégia de continuidade para as próximas semanas","Metas diárias de água, sono e rotina","Conteúdo complementar para uma vida mais ativa","Acesso digital ao material completo"];
    app.innerHTML=`<main class="offer-page">
      <section class="offer-hero"><div class="offer-container offer-narrow">${logo()}<div class="condition"><div><span>Sua condição atual</span><strong>25%</strong></div><i>→</i><div><span>Seu potencial de consistência</span><strong>90%</strong></div></div>${timer()}<h1>${name?`${name}, seu`:"Seu"} plano alimentar personalizado está pronto!</h1><p class="hero-copy">Organizamos suas respostas em uma experiência prática para acompanhar pelo celular.</p>${buyBox()}</div></section>
      <section><div class="offer-container offer-narrow"><h2>Como funciona o plano?</h2><p class="section-intro">Você recebe uma sequência organizada de refeições, orientações e metas construída a partir das respostas dadas no quiz.</p><div class="how-card"><span>1</span><div><h3>Acesse o conteúdo</h3><p>Abra o material no celular e consulte a etapa indicada para cada momento da sua rotina.</p></div></div><div class="how-card"><span>2</span><div><h3>Siga a organização diária</h3><p>Use as sugestões de refeições e compras como referência para planejar seus próximos dias.</p></div></div><div class="how-card"><span>3</span><div><h3>Acompanhe sua constância</h3><p>Registre seu progresso e ajuste a rotina de acordo com suas necessidades.</p></div></div><h3 class="included-title">Tudo o que você recebe:</h3><ul class="inclusion-list">${items.map(x=>`<li><span>✓</span><strong>${esc(x)}</strong></li>`).join("")}</ul>${timer()}${buyBox()}</div></section>
      <section class="visual-section"><div class="offer-container offer-narrow"><p class="eyebrow">UMA EXPERIÊNCIA VISUAL E SIMPLES</p><h2>Veja as mudanças que uma rotina consistente pode apoiar</h2><div class="wide-image">${asset("visibleChange","Imagem autorizada de evolução")}</div><p class="image-caption">Insira aqui a imagem autorizada que você está preparando.</p></div></section>
      <section><div class="offer-container offer-narrow"><p class="eyebrow">HISTÓRIAS REAIS</p><h2>Veja a experiência de quem já começou</h2>${testimonials(4)}${timer()}${buyBox()}</div></section>
      <section class="faq-section"><div class="offer-container offer-narrow"><h2>Ficou com alguma dúvida?</h2><p class="centered">Veja as perguntas mais frequentes</p><div class="faq"><details open><summary>O que encontrarei no plano?</summary><p>Refeições, receitas, organização de compras, metas e conteúdos complementares.</p></details><details><summary>Como minhas respostas são utilizadas?</summary><p>Elas ajudam a organizar a experiência conforme seu objetivo, rotina e preferências registradas.</p></details><details><summary>Quando recebo o acesso?</summary><p>O acesso é liberado conforme as informações exibidas no checkout após a confirmação do pagamento.</p></details><details><summary>Consigo acompanhar pelo celular?</summary><p>Sim. O conteúdo foi estruturado para consulta em telas de celular.</p></details><details><summary>Preciso fazer exercícios?</summary><p>A atividade física é complementar e deve respeitar seus limites e a orientação de um profissional.</p></details><details><summary>Os resultados são iguais para todo mundo?</summary><p>Não. Resultados variam conforme rotina, características individuais e constância.</p></details></div></div></section>
      <section><div class="offer-container offer-narrow guarantee"><div class="guarantee-image">${asset("guarantee","Imagem autorizada da garantia")}</div><div><p class="eyebrow">COMPRA PROTEGIDA</p><h2>Garantia de reembolso</h2><p>Consulte no checkout o prazo e todas as condições aplicáveis à garantia.</p></div></div></section>
      <section class="last-call"><div class="offer-container offer-narrow"><p class="eyebrow">SEU PLANO JÁ ESTÁ PRONTO</p><h2>Comece quando estiver preparado</h2><p class="centered">Revise os detalhes e conclua o acesso pelo ambiente seguro de pagamento.</p>${timer()}${buyBox()}</div></section>
      <footer>© 2026 ${esc(CONFIG.brand)}. Conteúdo educativo. Resultados variam.</footer>
    </main>`;
    window.scrollTo({top:0});startOfferTimer();
  }
  if(location.hash==="#oferta"||sessionStorage.getItem("carnifit_completed")==="1")renderOffer();else renderStep();
})();
